Repository swyp-season8-4-team/backend, pull requests merged in 2025-04, with the labels that each got.

#237 [FEATURE] 관리자 신고 관리 기능 구현
  src/main/java/org/swyp/dessertbee/admin/report/controller/MateReportAdminController.java
  src/main/java/org/swyp/dessertbee/admin/report/service/MateReportAdminService.java
  src/main/java/org/swyp/dessertbee/admin/report/service/MateReportAdminServiceImpl.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateReportResponse.java
  src/main/java/org/swyp/dessertbee/community/mate/repository/MateReplyRepository.java
  src/main/java/org/swyp/dessertbee/community/mate/repository/MateReportRepository.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateMemberServiceImpl.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyService.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyServiceImpl.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateService.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
Labels: enhancement

#246 [FIX] 엔진엑스 변수 할당 방식 변경
  nginx/conf/default.conf.template
Labels: bug

#242 [FIX] 가게 링크 관련 변경사항 리팩토링
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/common/repository/UserSearchHistoryRepository.java
  src/main/java/org/swyp/dessertbee/common/service/ImageService.java
  src/main/java/org/swyp/dessertbee/common/service/SearchServiceImpl.java
  src/main/java/org/swyp/dessertbee/community/mate/repository/MateRepository.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateMemberServiceImpl.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyServiceImpl.java
  src/main/java/org/swyp/dessertbee/community/mate/service/SavedMateServiceImpl.java
  src/main/java/org/swyp/dessertbee/community/review/controller/ReviewReplyController.java
  src/main/java/org/swyp/dessertbee/community/review/service/ReviewReplyService.java
  src/main/java/org/swyp/dessertbee/community/review/service/ReviewService.java
  src/main/java/org/swyp/dessertbee/community/review/service/SavedReviewService.java
  src/main/java/org/swyp/dessertbee/migration/MigrationRunner.java
  src/main/java/org/swyp/dessertbee/migration/service/StoreLinkMigrationService.java
  src/main/java/org/swyp/dessertbee/seeder/StoreTagSeeder.java
  src/main/java/org/swyp/dessertbee/store/menu/converter/MenuConverter.java
  src/main/java/org/swyp/dessertbee/store/menu/dto/request/MenuCreateRequest.java
  src/main/java/org/swyp/dessertbee/store/menu/service/MenuServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/store/dto/request/BaseStoreRequest.java
  src/main/java/org/swyp/dessertbee/store/store/dto/request/StoreCreateRequest.java
  src/main/java/org/swyp/dessertbee/store/store/dto/request/StoreUpdateRequest.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreSummaryResponse.java
  src/main/java/org/swyp/dessertbee/store/store/entity/Store.java
  src/main/java/org/swyp/dessertbee/store/store/entity/StoreLink.java
  src/main/java/org/swyp/dessertbee/store/store/exception/StoreExceptions.java
  src/main/java/org/swyp/dessertbee/store/store/repository/SavedStoreRepository.java
  src/main/java/org/swyp/dessertbee/store/store/repository/StoreHolidayRepository.java
  src/main/java/org/swyp/dessertbee/store/store/repository/StoreLinkRepository.java
  src/main/java/org/swyp/dessertbee/store/store/repository/StoreOperatingHourRepository.java
  src/main/java/org/swyp/dessertbee/store/store/repository/StoreRepository.java
  src/main/java/org/swyp/dessertbee/store/store/repository/StoreTagRelationRepository.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/store/service/UserStoreServiceImpl.java
Labels: refactoring

#249 [FIX] 가게 운영시간 관련 리팩토링 +)기타 리팩토링
  src/main/java/org/swyp/dessertbee/common/controller/SearchController.java
  src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java
  src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java
  src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
  src/main/java/org/swyp/dessertbee/store/store/dto/request/BaseStoreRequest.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/BreakTimeResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/HolidayResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/OperatingHourResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java
  src/main/java/org/swyp/dessertbee/store/store/entity/RegularClosureType.java
  src/main/java/org/swyp/dessertbee/store/store/entity/Store.java
  src/main/java/org/swyp/dessertbee/store/store/entity/StoreBreakTime.java
  src/main/java/org/swyp/dessertbee/store/store/entity/StoreOperatingHour.java
  src/main/java/org/swyp/dessertbee/store/store/entity/StoreStatistics.java
  src/main/java/org/swyp/dessertbee/store/store/repository/SavedStoreRepository.java
  src/main/java/org/swyp/dessertbee/store/store/repository/StoreBreakTimeRepository.java
  src/main/java/org/swyp/dessertbee/store/store/repository/StoreOperatingHourRepository.java
  src/main/java/org/swyp/dessertbee/store/store/repository/StoreStatisticsRepository.java
  src/main/java/org/swyp/dessertbee/store/store/repository/StoreTagRelationRepository.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
Labels: refactoring

#250 [FIX] 디바이스 ID 발급을 통한 토큰 갱신 에러 처리
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/controller/OAuthController.java
  src/main/java/org/swyp/dessertbee/auth/dto/TokenResponse.java
  src/main/java/org/swyp/dessertbee/auth/dto/login/LoginResponse.java
  src/main/java/org/swyp/dessertbee/auth/entity/AuthEntity.java
  src/main/java/org/swyp/dessertbee/auth/exception/AuthExceptions.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java
  src/main/java/org/swyp/dessertbee/auth/repository/AuthRepository.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/OAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/common/util/CookieUtil.java
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
  src/main/java/org/swyp/dessertbee/preference/controller/PreferenceController.java
  src/main/java/org/swyp/dessertbee/user/controller/MbtiController.java
Labels: bug, enhancement

#258 [DOCS] 가게 쪽 dto 스키마 정리
  src/main/java/org/swyp/dessertbee/common/controller/SearchController.java
  src/main/java/org/swyp/dessertbee/common/dto/PopularSearchResponse.java
  src/main/java/org/swyp/dessertbee/common/dto/PopularSearchesList.java
  src/main/java/org/swyp/dessertbee/common/dto/UserSearchHistoryDto.java
  src/main/java/org/swyp/dessertbee/common/service/SearchService.java
  src/main/java/org/swyp/dessertbee/common/service/SearchServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/coupon/dto/request/CouponCreateRequest.java
  src/main/java/org/swyp/dessertbee/store/coupon/dto/response/CouponResponse.java
  src/main/java/org/swyp/dessertbee/store/coupon/entity/Coupon.java
  src/main/java/org/swyp/dessertbee/store/coupon/repository/CouponRepository.java
  src/main/java/org/swyp/dessertbee/store/menu/dto/request/MenuCreateRequest.java
  src/main/java/org/swyp/dessertbee/store/menu/dto/response/MenuResponse.java
  src/main/java/org/swyp/dessertbee/store/review/dto/request/StoreReviewUpdateRequest.java
  src/main/java/org/swyp/dessertbee/store/review/dto/response/StoreReviewResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/request/BaseStoreRequest.java
  src/main/java/org/swyp/dessertbee/store/store/dto/request/StoreCreateRequest.java
  src/main/java/org/swyp/dessertbee/store/store/dto/request/StoreUpdateRequest.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/SavedStoreResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreListLocationResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreMapResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreSummaryResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/UserStoreListResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/UserStoreListSimpleResponse.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
Labels: documentation

#260 [DOCS] 응답값 nullable 여부 추가
  src/main/java/org/swyp/dessertbee/store/menu/dto/request/MenuCreateRequest.java
  src/main/java/org/swyp/dessertbee/store/menu/dto/response/MenuResponse.java
  src/main/java/org/swyp/dessertbee/store/review/dto/response/StoreReviewResponse.java
  src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
  src/main/java/org/swyp/dessertbee/store/store/controller/UserStoreController.java
  src/main/java/org/swyp/dessertbee/store/store/dto/request/BaseStoreRequest.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/BreakTimeResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/HolidayResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/OperatingHourResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/SavedStoreResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreListLocationResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreMapResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreSummaryResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/UserStoreListResponse.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/UserStoreListSimpleResponse.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
Labels: documentation

#263 Chore/262 test domain connection setting
  .github/workflows/deploy.yml
  docker-compose.yml
  nginx/conf/default.conf.template
  src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java
  src/main/resources/application-release.yml
Labels: bug, enhancement

#268 docs : 유저 컨트롤러 및 dto 스웨거 업데이트
  src/main/java/org/swyp/dessertbee/user/controller/UserController.java
  src/main/java/org/swyp/dessertbee/user/dto/request/NicknameAvailabilityRequestDto.java
  src/main/java/org/swyp/dessertbee/user/dto/request/NicknameValidationRequestDto.java
  src/main/java/org/swyp/dessertbee/user/dto/response/NicknameAvailabilityResponseDto.java
  src/main/java/org/swyp/dessertbee/user/dto/response/UserDetailResponseDto.java
  src/main/java/org/swyp/dessertbee/user/dto/response/UserResponseDto.java
  src/main/java/org/swyp/dessertbee/user/entity/NicknameValidationPurpose.java
Labels: documentation

#279 [FEATURE] 가게 공지 기능 추가
  .gitignore
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java
  src/main/java/org/swyp/dessertbee/store/notice/controller/StoreNoticeController.java
  src/main/java/org/swyp/dessertbee/store/notice/dto/request/StoreNoticeRequest.java
  src/main/java/org/swyp/dessertbee/store/notice/dto/response/StoreNoticeResponse.java
  src/main/java/org/swyp/dessertbee/store/notice/entity/StoreNotice.java
  src/main/java/org/swyp/dessertbee/store/notice/exception/StoreNoticeExceptions.java
  src/main/java/org/swyp/dessertbee/store/notice/repository/StoreNoticeRepository.java
  src/main/java/org/swyp/dessertbee/store/notice/service/StoreNoticeService.java
  src/main/java/org/swyp/dessertbee/store/notice/service/StoreNoticeServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewService.java
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/store/dto/response/StoreDetailResponse.java
  src/main/java/org/swyp/dessertbee/store/store/entity/StoreLink.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
Labels: enhancement

#295 [FEATURE] 가게 통계 기능 (로그 저장, 설계)
  src/main/java/org/swyp/dessertbee/DessertBeeApplication.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java
  src/main/java/org/swyp/dessertbee/community/review/service/ReviewService.java
  src/main/java/org/swyp/dessertbee/statistics/common/exception/StoreLogExceptions.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/CommunityReviewLog.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/CouponUseLog.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/DessertMateLog.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/StoreReviewLog.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/StoreSaveLog.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/StoreStatistics.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/StoreViewLog.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/enums/DessertMateAction.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/enums/ReviewAction.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/enums/SaveAction.java
  src/main/java/org/swyp/dessertbee/statistics/store/event/CommunityReviewActionEvent.java
  src/main/java/org/swyp/dessertbee/statistics/store/event/CouponUseEvent.java
  src/main/java/org/swyp/dessertbee/statistics/store/event/MateActionEvent.java
  src/main/java/org/swyp/dessertbee/statistics/store/event/StoreReviewActionEvent.java
  src/main/java/org/swyp/dessertbee/statistics/store/event/StoreSaveActionEvent.java
  src/main/java/org/swyp/dessertbee/statistics/store/event/StoreViewEvent.java
  src/main/java/org/swyp/dessertbee/statistics/store/event/handler/CommunityReviewLogEventHandler.java
  src/main/java/org/swyp/dessertbee/statistics/store/event/handler/CouponUseLogEventHandler.java
  src/main/java/org/swyp/dessertbee/statistics/store/event/handler/MateLogEventHandler.java
  src/main/java/org/swyp/dessertbee/statistics/store/event/handler/StoreReviewLogEventHandler.java
  src/main/java/org/swyp/dessertbee/statistics/store/event/handler/StoreSaveLogEventHandler.java
  src/main/java/org/swyp/dessertbee/statistics/store/event/handler/StoreViewLogEventHandler.java
  src/main/java/org/swyp/dessertbee/statistics/store/repostiory/CommunityReviewLogRepository.java
  src/main/java/org/swyp/dessertbee/statistics/store/repostiory/CouponUseLogRepository.java
  src/main/java/org/swyp/dessertbee/statistics/store/repostiory/DessertMateLogRepository.java
  src/main/java/org/swyp/dessertbee/statistics/store/repostiory/StoreReviewLogRepository.java
  src/main/java/org/swyp/dessertbee/statistics/store/repostiory/StoreSaveLogRepository.java
  src/main/java/org/swyp/dessertbee/statistics/store/repostiory/StoreStatisticsRepository.java
  src/main/java/org/swyp/dessertbee/statistics/store/repostiory/StoreViewLogRepository.java
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/store/repository/StoreStatisticsRepository.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/store/service/UserStoreServiceImpl.java
Labels: enhancement

#301 [FIX] 워크플로우에 설정파일 덮어쓰기 옵션 활성화
  .github/workflows/deploy.yml
  nginx/conf/default.conf.template
Labels: bug, enhancement

#321 [FEATURE] 프로필 이미지와 함께 가입되는 multipart 회원가입 api 개발
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/dto/request/SignUpRequest.java
  src/main/java/org/swyp/dessertbee/auth/dto/request/SignUpWithProfileRequest.java
  src/main/java/org/swyp/dessertbee/auth/dto/response/LoginResponse.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/common/service/ImageService.java
Labels: documentation, enhancement, refactoring

#336 Feature/335 test account initializer
  src/main/java/org/swyp/dessertbee/config/TestAccountInitializer.java
Labels: enhancement

#347 [FIX] 유저 닉네임 중복 검사
  src/main/java/org/swyp/dessertbee/config/TestAccountInitializer.java
  src/main/java/org/swyp/dessertbee/user/repository/UserRepository.java
Labels: bug

#341 [FEATURE] Elasticsearch 기반 가게 검색 API 구현
  build.gradle
  docker-compose.yml
  src/main/java/org/swyp/dessertbee/common/exception/BusinessException.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/common/scheduler/SearchScheduler.java
  src/main/java/org/swyp/dessertbee/config/ElasticsearchConfig.java
  src/main/java/org/swyp/dessertbee/search/controller/SearchController.java
  src/main/java/org/swyp/dessertbee/search/controller/StoreSearchController.java
  src/main/java/org/swyp/dessertbee/search/doc/StoreDocument.java
  src/main/java/org/swyp/dessertbee/search/dto/PopularSearchResponse.java
  src/main/java/org/swyp/dessertbee/search/dto/PopularSearchesList.java
  src/main/java/org/swyp/dessertbee/search/dto/StoreSearchResponse.java
  src/main/java/org/swyp/dessertbee/search/dto/StoreSearchWrapperResponse.java
  src/main/java/org/swyp/dessertbee/search/dto/UserSearchHistoryDto.java
  src/main/java/org/swyp/dessertbee/search/entity/PopularSearchKeyword.java
  src/main/java/org/swyp/dessertbee/search/entity/UserSearchHistory.java
  src/main/java/org/swyp/dessertbee/search/exception/SearchExceptions.java
  src/main/java/org/swyp/dessertbee/search/repository/PopularSearchKeywordRepository.java
  src/main/java/org/swyp/dessertbee/search/repository/UserSearchHistoryRepository.java
  src/main/java/org/swyp/dessertbee/search/service/SearchService.java
  src/main/java/org/swyp/dessertbee/search/service/SearchServiceImpl.java
  src/main/java/org/swyp/dessertbee/search/service/StoreSearchService.java
  src/main/java/org/swyp/dessertbee/search/service/StoreSearchServiceImpl.java
  src/main/java/org/swyp/dessertbee/search/util/ElasticsearchIndexer.java
  src/main/java/org/swyp/dessertbee/search/util/StoreDocumentFactory.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/StoreStatistics.java
  src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java
  src/main/java/org/swyp/dessertbee/store/menu/repository/MenuRepository.java
  src/main/java/org/swyp/dessertbee/store/menu/service/MenuServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-release.yml
Labels: enhancement

#351 [FIX] 토큰 갱신 오류 - 엔진엑스 deviceId 세팅
  nginx/conf/default.conf.template
Labels: bug

#355 [REFACTOR] 검색 api 수정
  build.gradle
  docker-compose.yml
  dump.rdb
  src/main/java/org/swyp/dessertbee/common/util/SearchUtil.java
  src/main/java/org/swyp/dessertbee/config/ElasticsearchConfig.java
  src/main/java/org/swyp/dessertbee/search/controller/StoreSearchController.java
  src/main/java/org/swyp/dessertbee/search/service/StoreSearchService.java
  src/main/java/org/swyp/dessertbee/search/service/StoreSearchServiceImpl.java
  src/main/java/org/swyp/dessertbee/search/util/ElasticsearchIndexer.java
  src/main/java/org/swyp/dessertbee/store/link/service/StoreLinkServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/menu/service/MenuServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
  src/main/java/org/swyp/dessertbee/store/store/handler/StoreImageHandlerImpl.java
  src/main/java/org/swyp/dessertbee/store/store/repository/StoreRepository.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreManageServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-release.yml
Labels: refactoring

#358 [FIX] UserDetailsService 빈 중복 경고
  src/main/java/org/swyp/dessertbee/auth/service/CustomUserDetailsService.java
Labels: bug

#359 [FEATURE] 특정 가게 저장 리스트 및 취향 태그 수정 API 추가
  src/main/java/org/swyp/dessertbee/store/saved/controller/UserStoreController.java
  src/main/java/org/swyp/dessertbee/store/saved/dto/request/UpdateSavedStoreListsRequest.java
  src/main/java/org/swyp/dessertbee/store/saved/repository/SavedStoreRepository.java
  src/main/java/org/swyp/dessertbee/store/saved/service/UserStoreService.java
  src/main/java/org/swyp/dessertbee/store/saved/service/UserStoreServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
Labels: enhancement

#361 [MERGE] merge dev into release (2025-04-27)
  src/main/java/org/swyp/dessertbee/auth/service/CustomUserDetailsService.java
  src/main/java/org/swyp/dessertbee/store/saved/controller/UserStoreController.java
  src/main/java/org/swyp/dessertbee/store/saved/dto/request/UpdateSavedStoreListsRequest.java
  src/main/java/org/swyp/dessertbee/store/saved/repository/SavedStoreRepository.java
  src/main/java/org/swyp/dessertbee/store/saved/service/UserStoreService.java
  src/main/java/org/swyp/dessertbee/store/saved/service/UserStoreServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
Labels: enhancement

#363 [CHORE] 동일 날짜 리뷰 등록 방지 예외처리 추가
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/store/review/exception/StoreReviewExceptions.java
  src/main/java/org/swyp/dessertbee/store/review/repository/StoreReviewRepository.java
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java
Labels: enhancement

#368 [FEATURE] 오늘 작성한 리뷰 여부 조회 API
  src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewService.java
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java
Labels: enhancement

#372 [FIX] 유저 가게 저장 여부 확인 시 단건 조회에서 모두 조회로 변경
  src/main/java/org/swyp/dessertbee/store/saved/repository/SavedStoreRepository.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreSupportServiceImpl.java
Labels: refactoring

#375 [CHORE] 스케줄러 멀티스레드 분리 및 Store Top Tag 배치 수동 실행 기능 추가
  src/main/java/org/swyp/dessertbee/common/controller/BatchTestController.java
  src/main/java/org/swyp/dessertbee/common/scheduler/SearchScheduler.java
  src/main/java/org/swyp/dessertbee/common/scheduler/StoreTopTagScheduler.java
  src/main/java/org/swyp/dessertbee/config/SchedulerConfig.java
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
  src/main/java/org/swyp/dessertbee/search/service/SearchServiceImpl.java
  src/main/java/org/swyp/dessertbee/statistics/common/scheduler/StoreStatisticsScheduler.java
  src/main/java/org/swyp/dessertbee/store/preference/repository/StoreTopTagRepository.java
  src/main/java/org/swyp/dessertbee/store/preference/service/StoreTopTagBatchService.java
  src/main/java/org/swyp/dessertbee/store/preference/service/StoreTopTagBatchTriggerService.java
  src/main/java/org/swyp/dessertbee/user/coupon/scheduler/CouponScheduler.java
Labels: refactoring

#378 [FEATURE] 유저 한줄리뷰 리스트 조회 API 구현
  src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java
  src/main/java/org/swyp/dessertbee/store/review/dto/response/UserReviewListResponse.java
  src/main/java/org/swyp/dessertbee/store/review/repository/StoreReviewRepository.java
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewService.java
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java
  src/main/java/org/swyp/dessertbee/user/controller/UserController.java
Labels: enhancement
