Repository swyp-season8-4-team/backend, pull requests merged in 2025-03, with the labels that each got.

#125 feat : 로그인 응답에 isPreferenceSet을 반환
  src/main/java/org/swyp/dessertbee/auth/dto/login/LoginResponse.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java
  src/main/java/org/swyp/dessertbee/preference/service/PreferenceService.java
Labels: enhancement

#126 refactor: 쿠키로 전달하던 리프레시 토큰을 바디값으로 전달
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/dto/login/LoginResponse.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java
Labels: enhancement

#131 [FEATURE] 카카오 프로필 이미지 등록
  build.gradle
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/controller/OAuthController.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/OAuthService.java
  src/main/java/org/swyp/dessertbee/common/service/ImageService.java
Labels: enhancement

#137 [FIX] 토큰 에러 처리
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTUtil.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorResponse.java
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
Labels: bug

#144 [FEATURE] 유저 역할 설정 및 삭제
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/role/service/RoleService.java
  src/main/java/org/swyp/dessertbee/role/service/UserRoleService.java
  src/main/java/org/swyp/dessertbee/user/controller/MbtiController.java
  src/main/java/org/swyp/dessertbee/user/controller/UserController.java
  src/main/java/org/swyp/dessertbee/user/dto/UserOAuthDto.java
  src/main/java/org/swyp/dessertbee/user/dto/request/NicknameValidationRequestDto.java
  src/main/java/org/swyp/dessertbee/user/dto/request/ProfileImageUpdateRequestDto.java
  src/main/java/org/swyp/dessertbee/user/dto/request/UserUpdateRequestDto.java
  src/main/java/org/swyp/dessertbee/user/dto/response/MbtiResponseDto.java
  src/main/java/org/swyp/dessertbee/user/dto/response/UserDetailResponseDto.java
  src/main/java/org/swyp/dessertbee/user/dto/response/UserResponseDto.java
  src/main/java/org/swyp/dessertbee/user/service/MbtiService.java
  src/main/java/org/swyp/dessertbee/user/service/UserService.java
  src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
Labels: enhancement

#148 feat : 깃허브 자동 배포 파일 설정
  .github/workflows/deploy.yml
Labels: enhancement

#151 feat : PreAuthorize 예외처리
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/common/exception/GlobalExceptionHandler.java
Labels: enhancement

#160 Feature/159 dev login
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTUtil.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/user/service/UserService.java
  src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
Labels: enhancement

#170 [REFACTOR] userRole service method apply
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
Labels: enhancement

#182 [FEATURE] userUuid를 토큰 payload에 삽입
  src/main/java/org/swyp/dessertbee/auth/dto/userdetails/CustomUserDetails.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTUtil.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/CustomUserDetailsService.java
  src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
Labels: enhancement, refactoring

#191 [FEATURE] SecurityConfig 경로 설정
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
Labels: enhancement

#208 [REFACTOR] 의도적인 취향 미설정 처리
  src/main/java/org/swyp/dessertbee/community/review/service/ReviewService.java
  src/main/java/org/swyp/dessertbee/preference/service/PreferenceService.java
  src/main/java/org/swyp/dessertbee/user/dto/response/UserDetailResponseDto.java
  src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java
  src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
Labels: enhancement, refactoring

#217 [DOCS] 스웨거 인증 에러 코드 추가
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/common/annotation/ApiErrorResponses.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/common/service/ImageService.java
  src/main/java/org/swyp/dessertbee/config/SwaggerErrorResponseCustomizer.java
  src/main/resources/application-prod.yml
Labels: documentation

#218 [FIX & DOCS]: swagger Failed to fetch 오류 해결
  src/main/java/org/swyp/dessertbee/config/SwaggerConfig.java
  src/main/resources/application-prod.yml
Labels: bug, documentation

#214 [REFACTOR] Setter 제거
  build.gradle
  src/main/java/org/swyp/dessertbee/auth/dto/oauth2/OAuthCodeRequest.java
  src/main/java/org/swyp/dessertbee/auth/entity/AuthEntity.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
  src/main/java/org/swyp/dessertbee/common/entity/BannerClick.java
  src/main/java/org/swyp/dessertbee/common/entity/Image.java
  src/main/java/org/swyp/dessertbee/common/entity/ReportCategory.java
  src/main/java/org/swyp/dessertbee/community/mate/entity/MateMember.java
  src/main/java/org/swyp/dessertbee/community/mate/entity/MateStatistics.java
  src/main/java/org/swyp/dessertbee/community/mate/entity/SavedMate.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateMemberService.java
  src/main/java/org/swyp/dessertbee/community/review/entity/ReviewContent.java
  src/main/java/org/swyp/dessertbee/community/review/entity/ReviewStatistics.java
  src/main/java/org/swyp/dessertbee/community/review/entity/SavedReview.java
  src/main/java/org/swyp/dessertbee/preference/entity/PreferenceEntity.java
  src/main/java/org/swyp/dessertbee/preference/entity/UserPreferenceEntity.java
  src/main/java/org/swyp/dessertbee/preference/service/PreferenceService.java
  src/main/java/org/swyp/dessertbee/role/entity/RoleEntity.java
  src/main/java/org/swyp/dessertbee/role/entity/UserRoleEntity.java
  src/main/java/org/swyp/dessertbee/store/coupon/entity/Coupon.java
  src/main/java/org/swyp/dessertbee/store/event/entity/Event.java
  src/main/java/org/swyp/dessertbee/store/menu/entity/Menu.java
  src/main/java/org/swyp/dessertbee/store/review/entity/StoreReview.java
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewService.java
  src/main/java/org/swyp/dessertbee/store/store/entity/SavedStore.java
  src/main/java/org/swyp/dessertbee/store/store/entity/Store.java
  src/main/java/org/swyp/dessertbee/store/store/entity/StoreHoliday.java
  src/main/java/org/swyp/dessertbee/store/store/entity/StoreOperatingHour.java
  src/main/java/org/swyp/dessertbee/store/store/entity/StoreStatistics.java
  src/main/java/org/swyp/dessertbee/store/store/entity/UserStoreList.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java
  src/main/java/org/swyp/dessertbee/user/dto/request/ProfileImageUpdateRequestDto.java
  src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java
  src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
Labels: refactoring

#220 [DOCS] Oauth 스웨거 문서 적용
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/controller/OAuthController.java
  src/main/java/org/swyp/dessertbee/auth/exception/AuthExceptions.java
  src/main/java/org/swyp/dessertbee/auth/exception/OAuthExceptions.java
  src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/OAuthService.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
Labels: documentation, enhancement

#224 [REFACTOR] 가게 관련 에러코드 및 스웨거 문서 정리
  src/main/java/org/swyp/dessertbee/common/controller/SearchController.java
  src/main/java/org/swyp/dessertbee/common/entity/Image.java
  src/main/java/org/swyp/dessertbee/common/entity/ImageType.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/common/exception/SearchExceptions.java
  src/main/java/org/swyp/dessertbee/common/service/SearchService.java
  src/main/java/org/swyp/dessertbee/preference/exception/PreferenceExceptions.java
  src/main/java/org/swyp/dessertbee/store/event/controller/EventController.java
  src/main/java/org/swyp/dessertbee/store/event/dto/request/EventCreateRequest.java
  src/main/java/org/swyp/dessertbee/store/event/dto/response/EventResponse.java
  src/main/java/org/swyp/dessertbee/store/event/entity/Event.java
  src/main/java/org/swyp/dessertbee/store/event/repository/EventRepository.java
  src/main/java/org/swyp/dessertbee/store/event/service/EventService.java
  src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java
  src/main/java/org/swyp/dessertbee/store/menu/exception/MenuExceptions.java
  src/main/java/org/swyp/dessertbee/store/menu/service/MenuService.java
  src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java
  src/main/java/org/swyp/dessertbee/store/review/exception/StoreReviewExceptions.java
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewService.java
  src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
  src/main/java/org/swyp/dessertbee/store/store/controller/UserStoreController.java
  src/main/java/org/swyp/dessertbee/store/store/entity/StoreStatistics.java
  src/main/java/org/swyp/dessertbee/store/store/exception/StoreExceptions.java
  src/main/java/org/swyp/dessertbee/store/store/exception/UserStoreExceptions.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java
  src/main/java/org/swyp/dessertbee/store/store/service/UserStoreService.java
  src/main/java/org/swyp/dessertbee/user/exception/UserExceptions.java
Labels: refactoring

#222 [CHORE] 도커 세팅
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  docker-compose.prod.yml
  src/main/java/org/swyp/dessertbee/auth/controller/OAuthController.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
Labels: enhancement

#230 Fix/171 docker setting error code lombok
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/preference/entity/PreferenceEntity.java
Labels: bug

#226 [DOCS] 이메일, 취향, mbti 스웨거 적용
  src/main/java/org/swyp/dessertbee/common/controller/DevController.java
  src/main/java/org/swyp/dessertbee/email/controller/EmailVerificationController.java
  src/main/java/org/swyp/dessertbee/preference/controller/PreferenceController.java
  src/main/java/org/swyp/dessertbee/preference/dto/PreferenceResponseDto.java
  src/main/java/org/swyp/dessertbee/user/controller/MbtiController.java
  src/main/java/org/swyp/dessertbee/user/dto/response/MbtiResponseDto.java
Labels: documentation

#231 [REFACTOR] 가게 쪽 서비스 구현체 분리
  src/main/java/org/swyp/dessertbee/common/repository/UserSearchHistoryRepository.java
  src/main/java/org/swyp/dessertbee/common/service/SearchService.java
  src/main/java/org/swyp/dessertbee/common/service/SearchServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/menu/controller/MenuController.java
  src/main/java/org/swyp/dessertbee/store/menu/service/MenuService.java
  src/main/java/org/swyp/dessertbee/store/menu/service/MenuServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/review/controller/StoreReviewController.java
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewService.java
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreService.java
  src/main/java/org/swyp/dessertbee/store/store/service/StoreServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/store/service/UserStoreService.java
  src/main/java/org/swyp/dessertbee/store/store/service/UserStoreServiceImpl.java
  src/main/java/org/swyp/dessertbee/user/controller/UserController.java
Labels: refactoring

#223 [REFACTOR] 커뮤니티 api 스웨거 추가 및 serviceImpl 작업
  src/main/java/org/swyp/dessertbee/community/mate/controller/MateController.java
  src/main/java/org/swyp/dessertbee/community/mate/controller/MateMemberController.java
  src/main/java/org/swyp/dessertbee/community/mate/controller/MateReplyController.java
  src/main/java/org/swyp/dessertbee/community/mate/controller/SavedMateController.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateMemberService.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateMemberServiceImpl.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyService.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyServiceImpl.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateService.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java
  src/main/java/org/swyp/dessertbee/community/mate/service/SavedMateService.java
  src/main/java/org/swyp/dessertbee/community/mate/service/SavedMateServiceImpl.java
  src/main/java/org/swyp/dessertbee/community/review/controller/ReviewController.java
  src/main/java/org/swyp/dessertbee/community/review/controller/ReviewReplyController.java
  src/main/java/org/swyp/dessertbee/community/review/controller/SavedReviewController.java
Labels: documentation

#233 [CHORE] 릴리즈 서버 생성, 엔진엑스 도커 컨테이너로 관리
  .github/workflows/deploy.yml
  docker-compose.prod.yml
  docker-compose.yml
  nginx/conf/default.conf.template
  nginx/nginx.conf
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-release.yml
  src/main/resources/application.yml
Labels: enhancement

#239 [HOTFIX] 엔진엑스 설정에 스웨거 문서 경로 명시적 허용
  nginx/conf/default.conf.template
  src/main/resources/application.yml
Labels: bug, documentation

#243 chore : swagger경로 shouldNotFilter에 추가
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java
Labels: enhancement
