Repository swyp-season8-4-team/backend, pull requests merged in 2025-05, with the labels that each got.

#380 [FEAT] Apple Social Login
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/org/swyp/dessertbee/auth/controller/OAuthController.java
  src/main/java/org/swyp/dessertbee/auth/dto/request/AppleLoginRequest.java
  src/main/java/org/swyp/dessertbee/auth/enums/AuthProvider.java
  src/main/java/org/swyp/dessertbee/auth/oauth2/AppleResponse.java
  src/main/java/org/swyp/dessertbee/auth/repository/AuthRepository.java
  src/main/java/org/swyp/dessertbee/auth/service/AppleOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/OAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/static/apple-oauth-test.html
Labels: documentation, enhancement

#381 [MERGE] 애플 소셜 로그인 서버 PUSH
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/org/swyp/dessertbee/auth/controller/OAuthController.java
  src/main/java/org/swyp/dessertbee/auth/dto/request/AppleLoginRequest.java
  src/main/java/org/swyp/dessertbee/auth/enums/AuthProvider.java
  src/main/java/org/swyp/dessertbee/auth/oauth2/AppleResponse.java
  src/main/java/org/swyp/dessertbee/auth/repository/AuthRepository.java
  src/main/java/org/swyp/dessertbee/auth/service/AppleOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/OAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
  src/main/resources/static/apple-oauth-test.html
Labels: enhancement

#393 [FIX] 가게 이미지 삭제 오류 해결
  src/main/java/org/swyp/dessertbee/common/service/ImageService.java
  src/main/java/org/swyp/dessertbee/store/store/handler/StoreImageHandlerImpl.java
Labels: bug

#383 [REFACTOR] 관리자 신고 관리 기능 리팩토링
  src/main/java/org/swyp/dessertbee/admin/report/controller/MateReportAdminController.java
  src/main/java/org/swyp/dessertbee/admin/report/dto/response/MateReplyReportCountResponse.java
  src/main/java/org/swyp/dessertbee/admin/report/dto/response/MateReportCountResponse.java
  src/main/java/org/swyp/dessertbee/admin/report/dto/response/ReportActionResponse.java
  src/main/java/org/swyp/dessertbee/admin/report/service/MateReportAdminService.java
  src/main/java/org/swyp/dessertbee/admin/report/service/MateReportAdminServiceImpl.java
  src/main/java/org/swyp/dessertbee/admin/user/service/UserAdminService.java
  src/main/java/org/swyp/dessertbee/admin/user/service/UserAdminServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
  src/main/java/org/swyp/dessertbee/common/aop/CheckWriteRestriction.java
  src/main/java/org/swyp/dessertbee/common/aop/WriteRestrictionAspect.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/community/mate/repository/MateReportRepository.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyService.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyServiceImpl.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateService.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java
  src/main/java/org/swyp/dessertbee/email/service/WarningMailService.java
  src/main/java/org/swyp/dessertbee/email/service/WarningMailServiceImpl.java
  src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java
  src/main/resources/templates/mail/warning-email.html
Labels: enhancement

#419 [FIX] 가게 휴무일 등록 양식 수정
  src/main/java/org/swyp/dessertbee/store/schedule/dto/HolidayResponse.java
  src/main/java/org/swyp/dessertbee/store/schedule/entity/StoreHoliday.java
  src/main/java/org/swyp/dessertbee/store/schedule/service/StoreScheduleServiceImpl.java
  src/main/java/org/swyp/dessertbee/store/store/dto/request/BaseStoreRequest.java
Labels: refactoring

#409 [FEATURE] 기존 web Apple OAuth에 App 로직 추가
  src/main/java/org/swyp/dessertbee/auth/controller/AppleCallbackTestController.java
  src/main/java/org/swyp/dessertbee/auth/controller/OAuthController.java
  src/main/java/org/swyp/dessertbee/auth/dto/response/LoginResponse.java
  src/main/java/org/swyp/dessertbee/auth/service/AppleOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/OAuthService.java
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-release.yml
  src/main/resources/application.yml
Labels: enhancement

#425 [FIX] 요청 dto @Valid 체크 추가
  src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
  src/main/java/org/swyp/dessertbee/store/store/dto/request/BaseStoreRequest.java
Labels: refactoring

#428 [Feature] 디저트메이트 댓글 blockedByAuthorYn 필드 추가
  src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateAcceptRequest.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateAppReplyCreateRequest.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateBannedRequest.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateCreateRequest.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateRejectRequest.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/request/MateReplyCreateRequest.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateAppReplyPageResponse.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateAppReplyResponse.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateDetailResponse.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateMemberResponse.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateReplyPageResponse.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateReplyResponse.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateReportResponse.java
  src/main/java/org/swyp/dessertbee/community/mate/dto/response/MateResponse.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateReplyServiceImpl.java
  src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java
Labels: enhancement

#430 [FIX] 차단한 사용자가 작성한 한줄리뷰 필터링
  src/main/java/org/swyp/dessertbee/store/review/service/StoreReviewServiceImpl.java
Labels: bug

#434 [FIX] 가게 한줄/커뮤니티 리뷰 차단사용자 필터링 로직 추가
  src/main/java/org/swyp/dessertbee/store/store/service/StoreSupportServiceImpl.java
Labels: bug

#441 [FIX] 인증서 갱신 자동화 Flow
  .github/workflows/deploy.yml
  docker-compose.yml
  nginx/conf/default-http-only.conf.template
  nginx/conf/default.conf.template
  ssl/renew-ssl.sh
  ssl/setup-ssl.sh
  ssl/ssl-health-check.sh
Labels: enhancement, :bug: bug

#447 feat: 토큰 응답에 refreshExpiresIn 추가 및 keepLoggedIn 기반 DB 저장 구현
  src/main/java/org/swyp/dessertbee/auth/dto/response/LoginResponse.java
  src/main/java/org/swyp/dessertbee/auth/service/AppleOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
Labels: bug, enhancement

#446 [FEAT] 워크플로우 단계별 분리
  .github/workflows/deploy.yml
  scripts/deploy-application.sh
  scripts/health-check.sh
  scripts/setup-ssl-deployment.sh
  scripts/setup-ssl-renewal.sh
  scripts/setup-system.sh
  scripts/verify-deployment.sh
Labels: documentation, enhancement, refactoring

#448 [MERGE] DEV TO RELEASE : 워크 플로우 분리, refreshExpires
  .github/workflows/deploy.yml
  scripts/deploy-application.sh
  scripts/health-check.sh
  scripts/setup-ssl-deployment.sh
  scripts/setup-ssl-renewal.sh
  scripts/setup-system.sh
  scripts/verify-deployment.sh
  src/main/java/org/swyp/dessertbee/auth/dto/response/LoginResponse.java
  src/main/java/org/swyp/dessertbee/auth/service/AppleOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
Labels: enhancement, :bug: bug

#450 fix: 배포 시 헬스체크 파싱 오류 및 무한 대기 문제 해결
  scripts/health-check.sh
  src/main/java/org/swyp/dessertbee/config/HealthController.java
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
Labels: :bug: bug
