Repository swyp-season8-4-team/backend, pull requests merged in 2025-02, with the labels that each got.

#12 Feature/7 o auth access token
  build.gradle
  src/main/java/org/swyp/dessertbee/.DS_Store
  src/main/java/org/swyp/dessertbee/DessertBeeApplication.java
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/controller/OAuth2Controller.java
  src/main/java/org/swyp/dessertbee/auth/dto/CustomOAuth2User.java
  src/main/java/org/swyp/dessertbee/auth/dto/KakaoResponse.java
  src/main/java/org/swyp/dessertbee/auth/dto/LoginResponse.java
  src/main/java/org/swyp/dessertbee/auth/dto/OAuth2AuthorizationRequest.java
  src/main/java/org/swyp/dessertbee/auth/dto/OAuth2CallbackRequest.java
  src/main/java/org/swyp/dessertbee/auth/dto/OAuth2Response.java
  src/main/java/org/swyp/dessertbee/auth/dto/TokenRequest.java
  src/main/java/org/swyp/dessertbee/auth/dto/TokenResponse.java
  src/main/java/org/swyp/dessertbee/auth/entity/AuthEntity.java
  src/main/java/org/swyp/dessertbee/auth/entity/EmailVerificationEntity.java
  src/main/java/org/swyp/dessertbee/auth/entity/EmailVerificationPurpose.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTUtil.java
  src/main/java/org/swyp/dessertbee/auth/oauth2/CustomSuccessHandler.java
  src/main/java/org/swyp/dessertbee/auth/repository/AuthRepository.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/CustomOAuth2UserService.java
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
  src/main/java/org/swyp/dessertbee/config/SwaggerConfig.java
  src/main/java/org/swyp/dessertbee/role/entity/RoleEntity.java
  src/main/java/org/swyp/dessertbee/role/entity/UserRoleEntity.java
  src/main/java/org/swyp/dessertbee/role/repository/RoleRepository.java
  src/main/java/org/swyp/dessertbee/role/repository/UserRoleRepository.java
  src/main/java/org/swyp/dessertbee/role/service/RoleService.java
  src/main/java/org/swyp/dessertbee/role/service/UserRoleService.java
  src/main/java/org/swyp/dessertbee/seeder/RoleSeeder.java
  src/main/java/org/swyp/dessertbee/user/dto/UserDTO.java
  src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java
  src/main/java/org/swyp/dessertbee/user/repository/UserRepository.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: enhancement

#15 Feat/14 email verify api
  build.gradle
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTUtil.java
  src/main/java/org/swyp/dessertbee/config/EmailConfig.java
  src/main/java/org/swyp/dessertbee/config/ThymeleafConfig.java
  src/main/java/org/swyp/dessertbee/email/controller/EmailVerificationController.java
  src/main/java/org/swyp/dessertbee/email/dto/EmailVerificationRequestDto.java
  src/main/java/org/swyp/dessertbee/email/dto/EmailVerificationResponseDto.java
  src/main/java/org/swyp/dessertbee/email/dto/EmailVerifyRequestDto.java
  src/main/java/org/swyp/dessertbee/email/dto/EmailVerifyResponseDto.java
  src/main/java/org/swyp/dessertbee/email/entity/EmailVerificationEntity.java
  src/main/java/org/swyp/dessertbee/email/entity/EmailVerificationPurpose.java
  src/main/java/org/swyp/dessertbee/email/repository/EmailVerificationRepository.java
  src/main/java/org/swyp/dessertbee/email/service/EmailVerificationService.java
  src/main/java/org/swyp/dessertbee/email/service/EmailVerificationServiceImpl.java
  src/main/java/org/swyp/dessertbee/preference/entity/PreferenceEntity.java
  src/main/java/org/swyp/dessertbee/preference/entity/UserPreferenceEntity.java
  src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java
  src/main/resources/application.yml
  src/main/resources/templates/mail/verification-email.html
Labels: enhancement

#22 [Feature] JWT관련 로그인, 회원가입, 로그아웃, 비밀번호 변경 구현 #21
  .gitignore
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/controller/OAuth2Controller.java
  src/main/java/org/swyp/dessertbee/auth/dto/login/LoginRequest.java
  src/main/java/org/swyp/dessertbee/auth/dto/login/LoginResponse.java
  src/main/java/org/swyp/dessertbee/auth/dto/logout/LogoutRequest.java
  src/main/java/org/swyp/dessertbee/auth/dto/logout/LogoutResponse.java
  src/main/java/org/swyp/dessertbee/auth/dto/passwordreset/PasswordResetRequest.java
  src/main/java/org/swyp/dessertbee/auth/dto/signup/SignUpRequest.java
  src/main/java/org/swyp/dessertbee/auth/dto/signup/SignUpResponse.java
  src/main/java/org/swyp/dessertbee/auth/exception/AuthExceptions.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTUtil.java
  src/main/java/org/swyp/dessertbee/auth/oauth2/CustomSuccessHandler.java
  src/main/java/org/swyp/dessertbee/auth/repository/AuthRepository.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/CustomOAuth2UserService.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
  src/main/java/org/swyp/dessertbee/user/dto/UserDTO.java
  src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java
  src/main/java/org/swyp/dessertbee/user/repository/UserRepository.java
Labels: enhancement

#26 디저트메이트 수정 api 구현
  src/main/java/org/swyp/dessertbee/mate/controller/MateController.java
  src/main/java/org/swyp/dessertbee/mate/entity/Mate.java
  src/main/java/org/swyp/dessertbee/mate/service/MateService.java
Labels: enhancement

#30 [FIX & FEATURE] 인증관련 에러 핸들링, 경로 수정
  src/main/java/org/swyp/dessertbee/auth/controller/OAuth2Controller.java
  src/main/java/org/swyp/dessertbee/auth/dto/LoginResponse.java
  src/main/java/org/swyp/dessertbee/auth/dto/OAuth2AuthorizationRequest.java
  src/main/java/org/swyp/dessertbee/auth/dto/OAuth2CallbackRequest.java
  src/main/java/org/swyp/dessertbee/auth/dto/TokenRequest.java
  src/main/java/org/swyp/dessertbee/auth/exception/AuthExceptions.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
  src/main/java/org/swyp/dessertbee/common/exception/BusinessException.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorResponse.java
  src/main/java/org/swyp/dessertbee/common/exception/GlobalExceptionHandler.java
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
  src/main/java/org/swyp/dessertbee/email/controller/EmailVerificationController.java
  src/main/java/org/swyp/dessertbee/email/service/EmailVerificationServiceImpl.java
Labels: bug, enhancement

#33 [Feature] Data Seeding
  src/main/java/org/swyp/dessertbee/preference/repository/PreferenceRepository.java
  src/main/java/org/swyp/dessertbee/seeder/MbtiSeeder.java
  src/main/java/org/swyp/dessertbee/seeder/PreferenceSeeder.java
  src/main/java/org/swyp/dessertbee/seeder/RoleSeeder.java
  src/main/java/org/swyp/dessertbee/user/entity/MbtiEntity.java
  src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java
  src/main/java/org/swyp/dessertbee/user/repository/MbtiRepository.java
Labels: enhancement

#35 Feature/27 user api 2
  src/main/java/org/swyp/dessertbee/auth/dto/CustomOAuth2User.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java
  src/main/java/org/swyp/dessertbee/auth/service/CustomOAuth2UserService.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/user/controller/UserController.java
  src/main/java/org/swyp/dessertbee/user/dto/UserDetailResponseDto.java
  src/main/java/org/swyp/dessertbee/user/dto/UserOAuthDto.java
  src/main/java/org/swyp/dessertbee/user/dto/UserResponseDto.java
  src/main/java/org/swyp/dessertbee/user/dto/UserUpdateRequestDto.java
  src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java
  src/main/java/org/swyp/dessertbee/user/repository/UserRepository.java
  src/main/java/org/swyp/dessertbee/user/service/UserService.java
  src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
Labels: documentation

#37 Feature/36 user auth email validaton
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/email/entity/EmailVerificationEntity.java
  src/main/java/org/swyp/dessertbee/email/repository/EmailVerificationRepository.java
  src/main/java/org/swyp/dessertbee/email/service/EmailVerificationServiceImpl.java
  src/main/java/org/swyp/dessertbee/user/controller/UserController.java
  src/main/java/org/swyp/dessertbee/user/dto/NicknameValidationRequestDto.java
  src/main/java/org/swyp/dessertbee/user/entity/NicknameValidationPurpose.java
  src/main/java/org/swyp/dessertbee/user/repository/UserRepository.java
  src/main/java/org/swyp/dessertbee/user/service/UserService.java
  src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
Labels: enhancement

#45 [Feature] 유저 프로필 이미지
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/dto/login/LoginResponse.java
  src/main/java/org/swyp/dessertbee/auth/oauth2/CustomSuccessHandler.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/common/service/ImageService.java
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
  src/main/java/org/swyp/dessertbee/user/controller/UserController.java
  src/main/java/org/swyp/dessertbee/user/dto/ProfileImageUpdateRequestDto.java
  src/main/java/org/swyp/dessertbee/user/dto/UserDetailResponseDto.java
  src/main/java/org/swyp/dessertbee/user/dto/UserOAuthDto.java
  src/main/java/org/swyp/dessertbee/user/dto/UserResponseDto.java
  src/main/java/org/swyp/dessertbee/user/dto/UserUpdateRequestDto.java
  src/main/java/org/swyp/dessertbee/user/entity/MbtiEntity.java
  src/main/java/org/swyp/dessertbee/user/entity/NicknameValidationPurpose.java
  src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java
  src/main/java/org/swyp/dessertbee/user/service/UserService.java
  src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: bug, enhancement

#55 [FEATURE] MBTI, 선호도 관련 API
  src/main/java/org/swyp/dessertbee/preference/controller/PreferenceController.java
  src/main/java/org/swyp/dessertbee/preference/dto/PreferenceResponseDto.java
  src/main/java/org/swyp/dessertbee/preference/service/PreferenceService.java
  src/main/java/org/swyp/dessertbee/user/controller/MbtiController.java
  src/main/java/org/swyp/dessertbee/user/dto/MbtiResponseDto.java
  src/main/java/org/swyp/dessertbee/user/service/MbtiService.java
Labels: enhancement

#59 [FIX] 리프레시 토큰 만료시간 설정
  src/main/java/org/swyp/dessertbee/auth/dto/signup/SignUpRequest.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTUtil.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/CustomOAuth2UserService.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
  src/main/java/org/swyp/dessertbee/role/entity/RoleEntity.java
  src/main/java/org/swyp/dessertbee/role/entity/RoleType.java
  src/main/java/org/swyp/dessertbee/role/repository/RoleRepository.java
  src/main/java/org/swyp/dessertbee/role/service/RoleService.java
  src/main/java/org/swyp/dessertbee/role/service/UserRoleService.java
  src/main/java/org/swyp/dessertbee/seeder/RoleSeeder.java
  src/main/java/org/swyp/dessertbee/user/controller/UserController.java
  src/main/java/org/swyp/dessertbee/user/dto/UserDetailResponseDto.java
Labels: bug, enhancement

#81 refactor : 회원가입 시 로그인 응답과 동일하게 변경
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
Labels: enhancement

#104 [Fix] 리프레시 토큰 전달 방식 수정
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/dto/TokenResponse.java
  src/main/java/org/swyp/dessertbee/auth/dto/login/LoginResponse.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
  src/main/java/org/swyp/dessertbee/common/util/CookieUtil.java
Labels: bug, enhancement

#106 [REFACTOR] 유저 취향관련 설정 함수 분리
  src/main/java/org/swyp/dessertbee/preference/service/PreferenceService.java
  src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
Labels: enhancement

#115 [FEATURE] 토큰 및 http 파싱시 에러 처리
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/org/swyp/dessertbee/common/exception/GlobalExceptionHandler.java
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
Labels: enhancement

#117 [REFACTOR] OAuth 로그인 로직 수정
  src/main/java/org/swyp/dessertbee/auth/controller/OAuthController.java
  src/main/java/org/swyp/dessertbee/auth/dto/CustomOAuth2User.java
  src/main/java/org/swyp/dessertbee/auth/dto/oauth2/OAuthCodeRequest.java
  src/main/java/org/swyp/dessertbee/auth/jwt/JWTFilter.java
  src/main/java/org/swyp/dessertbee/auth/oauth2/CustomSuccessHandler.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
  src/main/java/org/swyp/dessertbee/auth/service/CustomOAuth2UserService.java
  src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/OAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/TokenService.java
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/config/SecurityConfig.java
  src/main/java/org/swyp/dessertbee/user/entity/UserEntity.java
  src/main/resources/application-dev.yml
  src/main/resources/static/kakao-oauth-test.html
Labels: enhancement
