Repository swyp-season8-4-team/backend, pull requests merged in 2025-06, with the labels that each got.

#452 [CHORE] 한줄리뷰 응답DTO 성별 필드 추가
  src/main/java/org/swyp/dessertbee/store/review/dto/response/StoreReviewResponse.java
Labels: :bug: bug

#456 [FIX] reset password request dto update
  src/main/java/org/swyp/dessertbee/auth/controller/AuthController.java
  src/main/java/org/swyp/dessertbee/auth/dto/request/PasswordResetRequest.java
  src/main/java/org/swyp/dessertbee/auth/dto/response/PasswordResetResponse.java
  src/main/java/org/swyp/dessertbee/auth/service/AuthServiceImpl.java
Labels: :bug: bug, :memo: docs

#465 [BUG] 디저트메이트 수정 시 장소 예외처리 추가
  src/main/java/org/swyp/dessertbee/community/mate/service/MateServiceImpl.java
Labels: :bug: bug

#467 [BUG] 디저트메이트 나간 사람 인원 줄어들지 않는 버그 수정
  src/main/java/org/swyp/dessertbee/community/mate/service/MateMemberServiceImpl.java
Labels: :bug: bug

#473 [REFACTOR] 가게 통계 API 고도화 및 기간별 추이 데이터 조회
  src/main/java/org/swyp/dessertbee/common/exception/ErrorCode.java
  src/main/java/org/swyp/dessertbee/community/review/service/ReviewService.java
  src/main/java/org/swyp/dessertbee/statistics/common/exception/StoreStatisticsLogExceptions.java
  src/main/java/org/swyp/dessertbee/statistics/common/scheduler/StoreStatisticsScheduler.java
  src/main/java/org/swyp/dessertbee/statistics/store/controller/StoreStatisticsAdminController.java
  src/main/java/org/swyp/dessertbee/statistics/store/controller/StoreStatisticsController.java
  src/main/java/org/swyp/dessertbee/statistics/store/dto/response/StoreStatisticsPeriodResponse.java
  src/main/java/org/swyp/dessertbee/statistics/store/dto/response/StoreStatisticsTrendResponse.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/StoreStatisticsPeriodic.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/StoreStatisticsTrend.java
  src/main/java/org/swyp/dessertbee/statistics/store/entity/enums/PeriodType.java
  src/main/java/org/swyp/dessertbee/statistics/store/repository/StoreStatisticsPeriodRepository.java
  src/main/java/org/swyp/dessertbee/statistics/store/repository/StoreStatisticsTrendRepository.java
  src/main/java/org/swyp/dessertbee/statistics/store/repostiory/StoreStatisticsHourlyRepository.java
  src/main/java/org/swyp/dessertbee/statistics/store/service/StoreStatisticsService.java
  src/main/java/org/swyp/dessertbee/store/store/controller/StoreController.java
  src/main/java/org/swyp/dessertbee/store/store/repository/StoreRepository.java
Labels: enhancement

#481 [MERGE] DEV TO RELEASE
  src/main/java/org/swyp/dessertbee/auth/controller/OAuthController.java
  src/main/java/org/swyp/dessertbee/auth/dto/request/OAuthCodeRequest.java
  src/main/java/org/swyp/dessertbee/auth/service/KakaoOAuthService.java
  src/main/java/org/swyp/dessertbee/auth/service/OAuthService.java
  src/main/java/org/swyp/dessertbee/store/saved/repository/UserStoreListRepository.java
  src/main/java/org/swyp/dessertbee/store/saved/service/UserStoreService.java
  src/main/java/org/swyp/dessertbee/store/saved/service/UserStoreServiceImpl.java
  src/main/java/org/swyp/dessertbee/user/controller/UserTestController.java
  src/main/java/org/swyp/dessertbee/user/repository/UserBlockRepository.java
  src/main/java/org/swyp/dessertbee/user/service/UserServiceImpl.java
  src/main/java/org/swyp/dessertbee/user/service/UserTestService.java
Labels: 🪢 merge
